### ISSUE TITLE
[2022.07.01] 프로그래머스 lv2 - 단체사진 찍기

### ISSUE THREAD

**Issue by ikjo93** [who-hoo/algorithm-study#261]
## 문제링크

https://programmers.co.kr/learn/courses/30/lessons/1835

## 난이도(있다면 기재)

레벨투!

**Comment by who-hoo** [comment]
어려워요,,,,,😢

**Comment by ikjo93** [comment]
어렵네요..😭 수료식 때 단체사진도 못 찍고 알고리즘에서도 단체사진은 못 찍을 것 같습니다..

**Comment by who-hoo** [comment]
### 🚧 제출마감 🚧 

💸 미제출자 : @Seokho-Ham @NB993 
수고하셨습니다😄👍
