### ISSUE TITLE
[보너스 문제] - 프로그래머스 "거리두기 확인하기"

### ISSUE THREAD

**Issue by Seokho-Ham** [who-hoo/algorithm-study#267]
## 문제링크

https://school.programmers.co.kr/learn/courses/30/lessons/81302

코로나 걸린 기념으로 거리두기 문제 제출합니다;;
문제 읽어보지도 않고 제목만 보고 출제했으니 난이도는 저도 모르겠습니다;; 뭔지 아시죠;;

**Comment by who-hoo** [comment]
안물안궁이지만 혹시 모르니 레베루2입니다(궁금해서 찾아봄)
