### ISSUE TITLE
[2022.02.24(목)] Leetcode - Longest Substring Without Repeating Characters

### ISSUE THREAD

**Issue by Seokho-Ham** [who-hoo/algorithm-study#27]
## 문제링크
[Longest Substring Without Repeating Characters](https://leetcode.com/explore/interview/card/top-interview-questions-medium/103/array-and-strings/779)

이번엔 문자열 문제입니닷

## 난이도(있다면 기재)
medium

**Comment by who-hoo** [comment]
문제가 이해 안가는데요...8ㅅ8
3번 예시 저를 이해시켜주실분...?

**Comment by Seokho-Ham** [comment]
중복되지 않는 문자들로 이루어진 가장 긴 문자열을 구하는 문제라고 이해하시면 될듯합니다!
