### ISSUE TITLE
[2022.07.15] 백준 - 이진 검색 트리

### ISSUE THREAD

**Issue by who-hoo** [who-hoo/algorithm-study#283]
## 문제링크
https://www.acmicpc.net/problem/5639

## 난이도(있다면 기재)
고르도화이부✋

**Comment by donggi-lee-bit** [comment]
ㅜ

**Comment by ak2j38** [comment]
이름부터 ㅠㅠ

**Comment by who-hoo** [comment]
세모인간의 선택이랄까

**Comment by jeremy0405** [comment]
https://www.acmicpc.net/problem/1991
비슷한 문제로 이것도 추천드립니다 :)

**Comment by donggi-lee-bit** [comment]
으렵다..

**Comment by who-hoo** [comment]
### 🚧 제출마감 🚧 

💸 미제출자 : 모두 제출하셨습니다👏👏👏 
수고하셨습니다😄👍
