### ISSUE TITLE
[2022.07.27] 백준 - 내려가기

### ISSUE THREAD

**Issue by ak2j38** [who-hoo/algorithm-study#316]
## 문제링크
[내려가기](https://www.acmicpc.net/problem/2096)

## 난이도(있다면 기재)
🔑 5 입니다! 화이팅~~

**Comment by donggi-lee-bit** [comment]
아얅!!!!

**Comment by who-hoo** [comment]
### 🚧 제출마감 🚧 

💸 미제출자 : 모두 제출하셨습니다👏👏👏 
수고하셨습니다😄👍
