### ISSUE TITLE
[2022.08.03] 백준 - 부분합

### ISSUE THREAD

**Issue by jeremy0405** [who-hoo/algorithm-study#329]
## 문제링크

https://www.acmicpc.net/problem/1806

## 난이도(있다면 기재)

G4

**Comment by who-hoo** [comment]
### 🚧 제출마감 🚧 

💸 미제출자 : @who-hoo(면접 이슈로 특별 사면,,, 일요일까지 꼭 제출하겠습니다)
수고하셨습니다😄👍
