### ISSUE TITLE
[2022.08.06] 프로그래머스 - 게임 맵 최단거리

### ISSUE THREAD

**Issue by Seokho-Ham** [who-hoo/algorithm-study#337]
## 문제링크

[게임 맵 최단거리](https://school.programmers.co.kr/learn/courses/30/lessons/1844?language=java)

## 난이도(있다면 기재)

Level 2

**Comment by who-hoo** [comment]
### 🚧 제출마감 🚧 

💸 미제출자 : @who-hoo(면접 이슈로 특별 사면,,, 일요일까지 꼭 제출하겠습니다)
수고하셨습니다😄👍
