### ISSUE TITLE
[2022.08.17] 프로그래머스 - [1차] 캐시

### ISSUE THREAD

**Issue by donggi-lee-bit** [who-hoo/algorithm-study#369]
## 문제링크

[프로그래머스 - [1차] 캐시](https://school.programmers.co.kr/learn/courses/30/lessons/17680)

## 난이도(있다면 기재)

난도2

**Comment by who-hoo** [comment]
### 🚧 제출마감 🚧 

💸 미제출자 : 모두 제출하셨습니다👏👏👏 
수고하셨습니다😄👍
