### ISSUE TITLE
[2022.08.24] 프로그래머스 - 두 큐 합 같게 만들기

### ISSUE THREAD

**Issue by ak2j38** [who-hoo/algorithm-study#387]
## 문제링크
카카오 블라인드 테크 인턴쉽 문제네요!
[두 큐 합 같게 만들기](https://school.programmers.co.kr/learn/courses/30/lessons/118667)
## 난이도(있다면 기재)
레베루 2

**Comment by who-hoo** [comment]
### 🚧 제출마감 🚧 

💸 미제출자 : 모두 제출하셨습니다👏👏👏 
수고하셨습니다😄👍
