### ISSUE TITLE
[2022.09.16] 프로그래머스 - 셔틀버스

### ISSUE THREAD

**Issue by leejohy-0223** [who-hoo/algorithm-study#444]
## 문제링크
https://school.programmers.co.kr/learn/courses/30/lessons/17678

## 난이도(있다면 기재)
🤢 Lv 3 🤢

**Comment by jeremy0405** [comment]
레벨 3은 반칙인데요.. 🥲

**Comment by who-hoo** [comment]
@Seokho-Ham 왜 제출 안하셨어요...? 이러면 안풀고 제출만한 제가 되게... 면목이 없어지는데요....
