### ISSUE TITLE
[2022.09.23] 프로그래머스 - 정수 삼각형

### ISSUE THREAD

**Issue by ikjo93** [who-hoo/algorithm-study#462]
## 문제링크

[프로그래머스 - 정수 삼각형](https://school.programmers.co.kr/learn/courses/30/lessons/43105)

## 난이도(있다면 기재)

레벨 뚜리! (에서 정답률이 제일 높은 문제라고 합니다!)

**Comment by donggi-lee-bit** [comment]
레벨 뜨리에 반감을 가질 것에 대한 부연설명 좋네요!! ㅋㅋㅋㅋ

**Comment by ak2j38** [comment]
백준에도 똑같은 문제가 있네요! ㅋㅋㅋ
[정수 삼각형](https://www.acmicpc.net/problem/1932)

**Comment by NB993** [comment]
아아.. 또.. 🫠
