### ISSUE TITLE
[2022.09.28] 프로그래머스 - 다단계 칫솔 판매

### ISSUE THREAD

**Issue by jeremy0405** [who-hoo/algorithm-study#477]
## 문제링크

https://school.programmers.co.kr/learn/courses/30/lessons/77486

## 난이도(있다면 기재)

level 3

**Comment by donggi-lee-bit** [comment]
ㅋㅋㅋㅋ 이 문제 벌써 닫으시면 어떡하지요!!

**Comment by who-hoo** [comment]
### 🚧 제출마감 🚧 

💸 미제출자 : 모두 제출하셨습니다👏👏👏 
수고하셨습니다😄👍
