### ISSUE TITLE
[2022.10.12] 프로그래머스 - 후보키

### ISSUE THREAD

**Issue by donggi-lee-bit** [who-hoo/algorithm-study#515]
## 문제링크

[후복희](https://school.programmers.co.kr/learn/courses/30/lessons/42890)

## 난이도(있다면 기재)

Lv.2

**Comment by who-hoo** [comment]
### 🚧 제출마감 🚧 

💸 미제출자 : 모두 제출하셨습니다👏👏👏 
수고하셨습니다😄👍
