### ISSUE TITLE
[2022.10.21] 프로그래머스 - 스티커 모으기(2)

### ISSUE THREAD

**Issue by ikjo93** [who-hoo/algorithm-study#535]
## 문제링크

[프로그래머스 - 스티커 모으기(2) (2018 서머/윈터 코딩 기출문제)](https://school.programmers.co.kr/learn/courses/30/lessons/12971)

## 난이도(있다면 기재)

Level 3 (도즈언...!)

**Comment by who-hoo** [comment]
### 🚧 제출마감 🚧 

💸 미제출자 : 모두 제출하셨습니다👏👏👏 
수고하셨습니다😄👍
