### ISSUE TITLE
[2022.11.09] 백준 - 벽 부수고 이동하기

### ISSUE THREAD

**Issue by donggi-lee-bit** [who-hoo/algorithm-study#585]
## 문제링크

[벽부이](https://www.acmicpc.net/problem/2206)

## 난이도(있다면 기재)

골3

**Comment by who-hoo** [comment]
### 🚧 제출마감 🚧 

💸 미제출자 : 모두 제출하셨습니다👏👏👏 (@jeremy0405 최종 발표 특별 사면입니다)
수고하셨습니다😄👍
