### ISSUE TITLE
[2022.11.11] 백준 - 치킨배달

### ISSUE THREAD

**Issue by leejohy-0223** [who-hoo/algorithm-study#587]
## 문제링크
https://www.acmicpc.net/problem/15686

## 난이도(있다면 기재)
금5

**Comment by who-hoo** [comment]
### 🚧 제출마감 🚧 

💸 미제출자 : 모두 제출하셨습니다👏👏👏 (@jeremy0405 최종 발표 특별 사면입니다)
수고하셨습니다😄👍
