### ISSUE TITLE
[2022.11.16] 백준 - 두 수의 합

### ISSUE THREAD

**Issue by ak2j38** [who-hoo/algorithm-study#601]
## 문제링크
[두 수의 합](https://www.acmicpc.net/problem/3273)

## 난이도(있다면 기재)
실버 3 -> 저번주에 어려웠으니까요!

**Comment by who-hoo** [comment]
### 🚧 제출마감 🚧 

💸 미제출자 : 모두 제출하셨습니다👏👏👏
수고하셨습니다😄👍
