### ISSUE TITLE
[2022.11.18] 프로그래머스 - 보행자 천국

### ISSUE THREAD

**Issue by ikjo93** [who-hoo/algorithm-study#607]
## 문제링크

[프로그래머스 - 보행자 천국](https://school.programmers.co.kr/learn/courses/30/lessons/1832)

## 난이도(있다면 기재)

레벨 뚜리!

**Comment by who-hoo** [comment]
### 🚧 제출마감 🚧 

💸 미제출자 : 모두 제출하셨습니다👏👏👏
수고하셨습니다😄👍
