### ISSUE TITLE
[2022.12.03] 구름 - 소수 찾기

### ISSUE THREAD

**Issue by who-hoo** [who-hoo/algorithm-study#637]
## 문제링크
구름 챌린지 재탕스 입니다ㅎㅎ
https://level.goorm.io/exam/159184/%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98%EB%A8%BC%EB%8D%B0%EC%9D%B4-%EC%86%8C%EC%88%98-%EC%B0%BE%EA%B8%B0/quiz/1

## 난이도(있다면 기재)
별 두개

**Comment by ikjo93** [comment]
오 구름 챌린지라는 건 처음 접해보네요 👍

**Comment by who-hoo** [comment]
### 🚧 제출마감 🚧 

💸 미제출자 : @Seokho-Ham @jeremy0405 
수고하셨습니다😄👍
