### ISSUE TITLE
[2022.02.14(월)] BOJ(2579) : 계단 오르기

### ISSUE THREAD

**Issue by donggi-lee-bit** [who-hoo/algorithm-study#8]
## 문제링크
(늦어서 죄송합니다 😢)
https://www.acmicpc.net/problem/2579

## 난이도(있다면 기재)

실버 3

파이팅!!

**Comment by who-hoo** [comment]
> 추가로 다음 출제자가 난이도 조절을 하는데 참고할 수 있도록, 이번 문제가 쉬웠는지 안쉬웠는지 이슈에 이모지로 피드백 부탁드립니다.
> - 👍 : 난이도를 더 올려주세요
> - 👎 : 난이도를 더 낮춰주세요  
> - 적당한 난이도였으면 이모지 X

> 출제자는 그냥 참고만 하시고, 그냥 본인이 내고 싶은 문제 편하게 맘대로 출제하셔도 됩니다ㅋㅋㅋ

비하 하는 것 아닙니다 동기...

**Comment by leejohy-0223** [comment]
dp 시러요 🙀

**Comment by donggi-lee-bit** [comment]
> dp 시러요 🙀
