### ISSUE TITLE
[2022.04.09 (토)] 프로그래머스 - 모음사전

### ISSUE THREAD

**Issue by Seokho-Ham** [who-hoo/algorithm-study#85]
## 문제링크

[모음사전] (https://programmers.co.kr/learn/courses/30/lessons/84512)

**Comment by who-hoo** [comment]
분명 쉬운 문제 내기로 약속 했잖아요...😢

**Comment by Seokho-Ham** [comment]
> 분명 쉬운 문제 내기로 약속 했잖아요...😢 

🫣
